// Extended mock schedule data for comprehensive weekly view
import { Schedule } from '../types/teacher';
import { mockTeacher } from './mockData';

export const extendedMockSchedule: Schedule[] = [
    // SENIN
    {
        id: '1',
        day: 'Senin',
        time: '07:00 - 07:45',
        class: 'XII IPA 1',
        subject: 'Matematika',
        teacher: mockTeacher.name,
        room: 'Ruang 12',
    },
    {
        id: '2',
        day: 'Senin',
        time: '07:45 - 08:30',
        class: 'XII IPA 1',
        subject: 'Matematika',
        teacher: mockTeacher.name,
        room: 'Ruang 12',
    },
    {
        id: '3',
        day: 'Senin',
        time: '10:15 - 11:00',
        class: 'XI IPA 2',
        subject: 'Fisika',
        teacher: mockTeacher.name,
        room: 'Lab Fisika',
    },
    {
        id: '4',
        day: 'Senin',
        time: '11:00 - 11:45',
        class: 'XI IPA 2',
        subject: 'Fisika',
        teacher: mockTeacher.name,
        room: 'Lab Fisika',
    },
    {
        id: '5',
        day: 'Senin',
        time: '13:00 - 13:45',
        class: 'X IPA 3',
        subject: 'Matematika',
        teacher: mockTeacher.name,
        room: 'Ruang 10',
    },

    // SELASA
    {
        id: '6',
        day: 'Selasa',
        time: '07:00 - 07:45',
        class: 'XII IPA 2',
        subject: 'Matematika',
        teacher: mockTeacher.name,
        room: 'Ruang 13',
    },
    {
        id: '7',
        day: 'Selasa',
        time: '07:45 - 08:30',
        class: 'XII IPA 2',
        subject: 'Matematika',
        teacher: mockTeacher.name,
        room: 'Ruang 13',
    },
    {
        id: '8',
        day: 'Selasa',
        time: '08:30 - 09:15',
        class: 'XI IPA 1',
        subject: 'Fisika',
        teacher: mockTeacher.name,
        room: 'Lab Fisika',
    },
    {
        id: '9',
        day: 'Selasa',
        time: '09:15 - 10:00',
        class: 'XI IPA 1',
        subject: 'Fisika',
        teacher: mockTeacher.name,
        room: 'Lab Fisika',
    },
    {
        id: '10',
        day: 'Selasa',
        time: '11:00 - 11:45',
        class: 'X IPA 1',
        subject: 'Matematika',
        teacher: mockTeacher.name,
        room: 'Ruang 8',
    },
    {
        id: '11',
        day: 'Selasa',
        time: '11:45 - 13:00',
        class: 'X IPA 1',
        subject: 'Matematika',
        teacher: mockTeacher.name,
        room: 'Ruang 8',
    },

    // RABU
    {
        id: '12',
        day: 'Rabu',
        time: '07:00 - 07:45',
        class: 'XII IPA 1',
        subject: 'Fisika',
        teacher: mockTeacher.name,
        room: 'Lab Fisika',
    },
    {
        id: '13',
        day: 'Rabu',
        time: '07:45 - 08:30',
        class: 'XII IPA 1',
        subject: 'Fisika',
        teacher: mockTeacher.name,
        room: 'Lab Fisika',
    },
    {
        id: '14',
        day: 'Rabu',
        time: '10:15 - 11:00',
        class: 'XI IPA 3',
        subject: 'Matematika',
        teacher: mockTeacher.name,
        room: 'Ruang 11',
    },
    {
        id: '15',
        day: 'Rabu',
        time: '11:00 - 11:45',
        class: 'XI IPA 3',
        subject: 'Matematika',
        teacher: mockTeacher.name,
        room: 'Ruang 11',
    },
    {
        id: '16',
        day: 'Rabu',
        time: '13:00 - 13:45',
        class: 'X IPA 2',
        subject: 'Fisika',
        teacher: mockTeacher.name,
        room: 'Lab Fisika',
    },
    {
        id: '17',
        day: 'Rabu',
        time: '13:45 - 14:30',
        class: 'X IPA 2',
        subject: 'Fisika',
        teacher: mockTeacher.name,
        room: 'Lab Fisika',
    },

    // KAMIS
    {
        id: '18',
        day: 'Kamis',
        time: '07:00 - 07:45',
        class: 'XII IPA 3',
        subject: 'Matematika',
        teacher: mockTeacher.name,
        room: 'Ruang 14',
    },
    {
        id: '19',
        day: 'Kamis',
        time: '07:45 - 08:30',
        class: 'XII IPA 3',
        subject: 'Matematika',
        teacher: mockTeacher.name,
        room: 'Ruang 14',
    },
    {
        id: '20',
        day: 'Kamis',
        time: '08:30 - 09:15',
        class: 'XI IPA 2',
        subject: 'Matematika',
        teacher: mockTeacher.name,
        room: 'Ruang 11',
    },
    {
        id: '21',
        day: 'Kamis',
        time: '09:15 - 10:00',
        class: 'XI IPA 2',
        subject: 'Matematika',
        teacher: mockTeacher.name,
        room: 'Ruang 11',
    },
    {
        id: '22',
        day: 'Kamis',
        time: '10:15 - 11:00',
        class: 'X IPA 3',
        subject: 'Fisika',
        teacher: mockTeacher.name,
        room: 'Lab Fisika',
    },
    {
        id: '23',
        day: 'Kamis',
        time: '11:00 - 11:45',
        class: 'X IPA 3',
        subject: 'Fisika',
        teacher: mockTeacher.name,
        room: 'Lab Fisika',
    },

    // JUMAT
    {
        id: '24',
        day: 'Jumat',
        time: '07:00 - 07:45',
        class: 'XII IPA 2',
        subject: 'Fisika',
        teacher: mockTeacher.name,
        room: 'Lab Fisika',
    },
    {
        id: '25',
        day: 'Jumat',
        time: '07:45 - 08:30',
        class: 'XII IPA 2',
        subject: 'Fisika',
        teacher: mockTeacher.name,
        room: 'Lab Fisika',
    },
    {
        id: '26',
        day: 'Jumat',
        time: '08:30 - 09:15',
        class: 'XI IPA 1',
        subject: 'Matematika',
        teacher: mockTeacher.name,
        room: 'Ruang 11',
    },
    {
        id: '27',
        day: 'Jumat',
        time: '09:15 - 10:00',
        class: 'XI IPA 1',
        subject: 'Matematika',
        teacher: mockTeacher.name,
        room: 'Ruang 11',
    },
    {
        id: '28',
        day: 'Jumat',
        time: '10:15 - 11:00',
        class: 'X IPA 1',
        subject: 'Fisika',
        teacher: mockTeacher.name,
        room: 'Lab Fisika',
    },
];
